
version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: standard
    filename: ./logs/lemanchot.log
    when: midnight
loggers:
  sysLogger:
    handlers: [console, file_handler]
    propagate: true
root:
  handlers: [console, file_handler]